template:
  path: budget.yaml
stack_name: budget-compute

parameters:
  budgetName: budget-compute
  emailAddress: "{{stack_group_config.notifications_email}}"
  budgetAmount: "{{stack_group_config.budgets.compute}}"
  serviceFilters:
    {{stack_group_config.services.compute}}

stack_tags:
  {{stack_group_config.default_stack_tags}}
