template:
  path: budget.yaml
stack_name: budget-other

parameters:
  budgetName: budget-other
  emailAddress: "{{stack_group_config.notifications_email}}"
  budgetAmount: "{{stack_group_config.budgets.other}}"
  serviceFilters:
    {{stack_group_config.services.other}}

stack_tags:
  {{stack_group_config.default_stack_tags}}
